import { mkdirSync, writeFileSync, appendFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import { confirm, isCancel } from '@clack/prompts'

// ─── sigil agent add ──────────────────────────────────────────────────────────

const SUPPORTED_AGENTS = ['claude-code'] as const
type AgentName = (typeof SUPPORTED_AGENTS)[number]

export type AgentResult = { created: string[]; skipped: string[]; appended: string[] }

const SIGIL_CLAUDE_BLOCK = `
## Sigil Spec

This project uses Sigil for AI-driven specification. The spec corpus lives alongside the implementation.

### Reading the corpus

Start from \`sigil.toml\`. The hierarchy is: doctrine → charters → sigils. Read all three layers before taking any action.

### Spec commands

- \`/author\` — enter spec authoring mode (may only edit \`.sigil\`, \`.charter\`, \`.doctrine\` files)
- \`/consumer\` — enter implementation mode (read corpus, then implement provisions precisely)

Run \`sigil validate sigil.toml\` to validate the corpus at any time.
`

const CLAUDE_MD_STUB = `<!-- Generated by \`sigil agent add claude-code\`. Update this file with your project-specific instructions and preferences. -->
${SIGIL_CLAUDE_BLOCK}`

const AUTHOR_COMMAND = `\
Load \`SIGIL-AUTHOR.md\` from the project root into your context. You are now in Sigil author mode.

In this mode:
- You may only create or edit files with extensions: \`.sigil\`, \`.charter\`, \`.doctrine\`
- Do not modify implementation code, tests, or configuration files
- Use the grammar and conventions in \`SIGIL-AUTHOR.md\` as your guide
- Run \`sigil validate sigil.toml\` after writing or editing any spec file
- Ambiguity is a defect — write provisions so there is exactly one valid interpretation

When you are done authoring and ready to implement, use /consumer.
`

const CONSUMER_COMMAND = `\
Load \`SIGIL-CONSUMER.md\` from the project root into your context. You are now in Sigil consumer mode.

In this mode:
1. Run \`sigil validate sigil.toml\` first. Do not proceed if there are errors.
2. Read the spec corpus starting from \`sigil.toml\`: doctrine → charters → sigils.
3. Produce an implementation plan based on the provisions in the sigil files.
4. Present the plan for approval before writing any code.
5. After approval, implement each provision precisely as specified.
6. If anything in the spec is ambiguous, flag it and ask — do not guess.

When you need to revise the spec, use /author.
`

export async function addAgent(agentName: string, outputDir: string): Promise<AgentResult> {
  if (!SUPPORTED_AGENTS.includes(agentName as AgentName)) {
    console.error(
      `Unknown agent: '${agentName}'. Supported agents: ${SUPPORTED_AGENTS.join(', ')}`
    )
    process.exit(1)
  }

  const created: string[] = []
  const skipped: string[] = []
  const appended: string[] = []

  function writeFile(relativePath: string, content: string): void {
    const fullPath = join(outputDir, relativePath)
    if (existsSync(fullPath)) {
      skipped.push(relativePath)
    } else {
      writeFileSync(fullPath, content, 'utf8')
      created.push(relativePath)
    }
  }

  if (agentName === 'claude-code') {
    mkdirSync(join(outputDir, '.claude', 'commands'), { recursive: true })
    writeFile('.claude/commands/author.md', AUTHOR_COMMAND)
    writeFile('.claude/commands/consumer.md', CONSUMER_COMMAND)

    const claudeMdPath = join(outputDir, 'CLAUDE.md')
    if (!existsSync(claudeMdPath)) {
      writeFileSync(claudeMdPath, CLAUDE_MD_STUB, 'utf8')
      created.push('CLAUDE.md')
    } else {
      const shouldAppend = await confirm({
        message: 'CLAUDE.md already exists. Append the Sigil block to it?',
      })
      if (!isCancel(shouldAppend) && shouldAppend) {
        appendFileSync(claudeMdPath, '\n' + SIGIL_CLAUDE_BLOCK, 'utf8')
        appended.push('CLAUDE.md')
      } else if (!isCancel(shouldAppend)) {
        console.log('\nAdd the following block to your CLAUDE.md:\n')
        console.log('─'.repeat(60))
        console.log(SIGIL_CLAUDE_BLOCK)
        console.log('─'.repeat(60))
      }
    }
  }

  return { created, skipped, appended }
}
